name:                websockets-example
version:             0.1.0.0
synopsis:            Example Websockets app
description:         Please see README.md
homepage:            https://github.com/parsonsmatt/websockets-example#readme
license:             BSD3
author:              Matt Parsons
maintainer:          parsonsmatt@gmail.com
copyright:           2016 Matt Parsons
category:            Web

ghc-options:
  - -Wall

default-extensions:
  - OverloadedStrings
  - RecordWildCards
  - NoImplicitPrelude
  - LambdaCase
  - FlexibleContexts

dependencies:
  - base >= 4.7 && < 5
  - protolude
  - text
  - wai
  - wai-app-static
  - wai-extra
  - wai-websockets
  - warp
  - websockets

library:
  source-dirs: src

executables:
  server:
    source-dirs:      app
    main:             Main.hs
    dependencies:
      - websockets-example
